#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
Report 50000 "Varelabel"
{
	AdditionalSearchTerms = 'Scanpan';
	Caption = 'Item label';
	WordLayout = './Layouts/Varelabel.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem(Integer;Integer)
		{
			MaxIteration = 25;
			DataItemTableView = sorting(Number);
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Integer; ReportForNavWriteDataItem('Integer',Integer)) {}
			column(BarCode; BarCodeTxt)
			{
				IncludeCaption = false;
			}
			column(ItemDescription; ItemDescriptionTxt)
			{
				IncludeCaption = false;
			}
			column(ItemNo; ItemNumber)
			{
				IncludeCaption = false;
			}
			column(ItemTranslation; ItemTranslationTxt)
			{
				IncludeCaption = false;
			}
			column(ItemUnitOfMeasure; ItemUnitOfMeasureCode)
			{
				IncludeCaption = false;
			}
			column(ItemUnitQuantity; ItemUnitQuantityInt)
			{
				IncludeCaption = false;
			}
			trigger OnPreDataItem();
			begin
				Integer.SetRange(Number, 1, NoOfCopiesInt);
				if NoOfCopiesInt = 0 then Error(NumberOfLabelsLbl);
				if NoOfCopiesInt > 25 then Error(MaxPrintOutLbl);
				//;
				Integer.SetView(ReportForNav.OnPreDataItemView('Integer',Integer));
			end;
			
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
			area(Content)
			{
				group(scanpan)
				{
					Caption = 'Scanpan';

					field(NoOfCopies; NoOfCopiesInt)
					{
						ApplicationArea = Basic;
						Caption = 'No. Of Copies';
						ToolTip = 'Select number of labels to print.';
					}

					field(ItemNo; ItemNumber)
					{
						ApplicationArea = Basic;
						Caption = 'Item No.';
						TableRelation = Item."No.";
						ToolTip = 'Select Item No.';

						trigger OnValidate()
						var
							Item: Record Item;
						begin
							Item.get(ItemNumber);
							ItemDescriptionTxt := Item.Description;
							BarCodeTxt := '';
							ItemUnitOfMeasureCode := '';
						end;

						trigger OnLookup(var Text: Text): Boolean
						var
							Item: Record Item;
						begin
							if page.RunModal(Page::"Item List", Item) = Action::LookupOK then begin
								ItemNumber := Item."No.";
								ItemDescriptionTxt := Item.Description;

								BarCodeTxt := '';
								ItemUnitOfMeasureCode := '';
							end;
						end;
					}
					field(ItemDescription; ItemDescriptionTxt)
					{
						ApplicationArea = Basic, Suite;
						Caption = 'Item Description';
						Editable = false;
					}
					field(ItemUnitOfMeasure; ItemUnitOfMeasureCode)
					{
						ApplicationArea = Basic;
						Caption = 'Item Unit';
						TableRelation = "Item Unit Of Measure"."Code";
						ToolTip = 'Select Item Unit.';

						trigger OnValidate()
						var

							ItemCrossReference: Record "Item Reference";

							ItemUOM: Record "Item Unit of Measure";
						begin
							ItemCrossReference.SetFilter("Item No.", ItemNumber);
							ItemCrossReference.SetFilter("Unit of Measure", ItemUnitOfMeasureCode);
							ItemCrossReference.SETRANGE("Reference Type", ItemCrossReference."Reference Type"::"Bar Code");
							ItemCrossReference.FindFirst();
							BarCodeTxt := ItemCrossReference."Reference No.";

							ItemUOM.Get(ItemNumber, ItemUnitOfMeasureCode);
							ItemUnitQuantityInt := ItemUOM."Qty. per Unit of Measure";
						END;



						trigger OnLookup(var Text: Text): Boolean
						var

							ItemCrossReference: Record "Item Reference";

							ItemUOM: Record "Item Unit of Measure";
						begin
							ItemCrossReference.RESET;
							ItemCrossReference.SETRANGE("Item No.", ItemNumber);
							ItemCrossReference.SETRANGE("Reference Type", ItemCrossReference."Reference Type"::"Bar Code");
							if page.RUNMODAL(0, ItemCrossReference) = ACTION::LookupOK then begin
								ItemUnitOfMeasureCode := ItemCrossReference."Unit of Measure";
								BarCodeTxt := ItemCrossReference."Reference No.";

								ItemUOM.Get(ItemNumber, ItemUnitOfMeasureCode);
								ItemUnitQuantityInt := ItemUOM."Qty. per Unit of Measure";
							end;
						end;
					}
					field(BarCode; BarCodeTxt)
					{
						ApplicationArea = Basic, Suite;
						Caption = 'Barcode';
						Editable = false;
					}
					field(ItemUnitQuantity; ItemUnitQuantityInt)
					{
						ApplicationArea = Basic, Suite;
						Caption = 'Unit of Measure Quantity';
						Editable = false;
						ToolTip = 'Displays Quantity of the selected unit.';
					}
					field(ItemTranslation; ItemTranslationTxt)
					{
						ApplicationArea = Basic, Suite;
						Caption = 'Item Translation';
						ToolTip = 'Select Item Translation or blank for Item Card description.';
						trigger OnValidate()
						var
							Item: Record Item;
							ItmTranslation: Record "Item Translation";
						begin
							ItmTranslation.SetFilter("Item No.", ItemNumber);
							ItmTranslation.SetFilter("Language Code", ItemTranslationTxt);
							if ItmTranslation.Get(ItemNumber, ItemTranslationTxt) then begin
								ItemDescriptionTxt := ItmTranslation.Description;
								ItemTranslationTxt := ItmTranslation."Language Code";
							end else begin
								Item.get(ItemNumber);
								ItemDescriptionTxt := Item.Description;
							end;
						end;


						trigger OnLookup(var Text: Text): Boolean
						var
							Item: Record Item;
							ItmTranslation: Record "Item Translation";
						begin
							ItmTranslation.SetFilter("Item No.", ItemNumber);
							IF page.RUNMODAL(0, ItmTranslation) = ACTION::LookupOK THEN BEGIN
								ItemDescriptionTxt := ItmTranslation.Description;
								ItemTranslationTxt := ItmTranslation."Language Code";
							end else begin
								Item.get(ItemNumber);
								ItemDescriptionTxt := Item.Description;
							end;
						end;
					}
				}
				group(Options)
				{
					Caption = 'Options';
				}
			}
		}

	}
	var
		ItemNumber: code[20];
		ItemSelected: code[20];
		ItemUnitOfMeasureCode: code[20];
		ItemUnitQuantityInt: Integer;

		NoOfCopiesInt: Integer;
		MaxPrintOutLbl: Label 'No more than 25 labels per print.';
		NumberOfLabelsLbl: label 'Select labels to print.';
		BarCodeTxt: Text[50];
		ItemDescriptionTxt: Text[100];
		ItemTranslationTxt: Text[100];

	trigger OnInitReport()
	begin
		NoOfCopiesInt := 1;
		ReportsForNavInit();

	end;

	trigger OnPostReport()
	begin

	end;

	trigger OnPreReport()
	begin
		ReportsForNavPre();
	end;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}






