





POST https://api.dsv.com/om/v2/Orders HTTP/1.1

Authorization: Basic ZHN2YXBpQHNjYW5wYW4uZGs6RHN2QXBpMTIh
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
DSV-Subscription-Key: c310d2301d654dcc9cb0bae4a7b0a20d

{
    "Order": {
        "IsCancelled": false,
        "OrderNumber": "PUBAPI-V2-B2",
        "OrderNumberSplit": 0,
        "OrderDate": "2019-07-02T23:00:00Z",
        "OrderGoodsDescription": "goods api",
        "TransportMode": "AIR",
        "ContainerMode": "LCL",
        "ServiceLevel": "SRV",
        "EstimatedExWorksDate": "2019-07-15T06:51:50.13Z",
        "ActualExWorksDate": "2019-07-02T06:51:50.13Z",
        "ExWorksRequiredBy": "2019-05-12T06:51:50.13Z",
        "DeliveryRequiredBy": "2019-07-02T06:51:50.13Z",
        "OriginCountry": null,
        "Incoterm": "INC",
        "AdditionalTerms": "AT",
        "AdditionalTermsUNLOCO": null,
        "ActualVolume": 20,
        "UnitOfVolume": "M3",
        "ActualWeight": 10,
        "UnitOfWeight": "KG",
        "TotalPacks": 1,
        "TotalQuantity": 50,
        "PackType": "PK",
        "FollowUpDate": "2019-07-02T06:51:50.13Z",
        "PortOfLoading": "KO",
        "PortOfDischarge": "PO",
        "Currency": "OC",
        "ClientType": "Buyer",
        "TotalValue": 200,
        "TotalInners": 30.5,
        "TotalOuters": 10,
        "BookingReference": null,
        "TransitWarehouse": null,
        "OnHandDate": null,
        "PlannerCode": "PC",
        "PlannerEmail": "planner@email.com",
        "WarehouseReceiptNumber": null,
        "VehicleRegistration": "vh",
        "TrailerNumber": "tr",
        "Seal": "seal",
        "ManifestNumber": "manifest",
        "BookedInNumber": "bookedin",
        "DispatchedDate": "2019-07-02T06:51:50.13Z",
        "EstimatedReceiptDate": "2019-07-02T06:51:50.13Z",
        "BookedInDate": "2019-07-02T06:51:50.13Z",
        "CutOffDate": "2019-07-02T06:51:50.13Z",
        "InvoiceDate": "2019-07-02T06:51:50.13Z",
        "InvoiceNumber": "inv",
        "ConfirmedDate": "2019-07-02T06:51:50.13Z",
        "ConfirmationNumber": "conf",
        "ContractNumber": "cont",
        "GoodsReceiptNumber": "goodsre",
        "GoodsReceiptDate": "2019-07-02T06:51:50.13Z",
        "AuthorisedBy": "auth",
        "AuthorisedToShip": "2019-07-02T06:51:50.13Z",
        "OrderType": "PO",
        "EarliestShipDate": null,
        "LatestShipDate": null,
        "PackLines": [{
            "PackageCount": 200,
            "PackType": "PCK",
            "ContainerPackingOrder": 0,
            "Weight": 20,
            "UnitOfWeight": "",
            "Length": 10,
            "Height": 20,
            "Width": 5,
            "UnitOfDimension": "",
            "Volume": 1,
            "UnitOfVolume": "CM3",
            "RefNumber": "REF",
            "Description": "",
            "DetailedDescription": null,
            "HarmonisedCode": "",
            "Origin": "",
            "CommodityCode": "",
            "ContainerNumber": "",
            "Outturn": 0,
            "OutturnedLength": 0,
            "OutturnedHeight": 0,
            "OutturnedWidth": 0,
            "OutturnedWeight": 0,
            "OutturnedVolume": 0,
            "OutturnComment": "",
            "Pillaged": 0,
            "Damaged": 0,
            "LoadingMeters": 30,
            "MarksAndNumbers": "marks",
            "ProductCode": "PC001",
            "DangerousGoodsRef": null,
            "NoOfPallets": 0,
            "PackIdentifier": "",
            "DocumentRemarks1": "",
            "DocumentRemarks2": "",
            "DocumentRemarks3": "",
            "Sequence": 0,
            "Stackable": true,
            "OrderLineNumber": 1,
            "CustomFields": [{
                "Name": "PK Addon1",
                "Type": "STR",
                "Value": "string"
            }],
            "PackageMarks": "packmarks"
        }],
        "CustomFields": [{
            "Name": "StringAddon",
            "Type": "STR",
            "Value": "string"
        }, {
            "Name": "DateAddon",
            "Type": "DAT",
            "Value": "2019-07-02T06:51:50.13Z"
        }, {
            "Name": "BoolAddon",
            "Type": "BOO",
            "Value": "true"
        }, {
            "Name": "IntAddon",
            "Type": "INT",
            "Value": "20"
        }, {
            "Name": "DecimalAddon",
            "Type": "DEC",
            "Value": "50.57"
        }],
        "RequiredInStore": "2019-07-02T06:51:50.13Z",
        "RequiredExWorks": "2019-07-02T06:51:50.13Z",
        "Parties": [{
            "Type": "Buyer",
            "Code": "POSTBUY",
            "IsActive": true,
            "FullName": "Buyer Name",
            "ClosestPort": "",
            "Currency": null,
            "PhoneNumber": "0123",
            "Email": null,
            "VATNumber": null,
            "RegisteredNumber": null
        }, {
            "Type": "Supplier",
            "Code": "POSTSUP",
            "IsActive": true,
            "FullName": "Supplier Name",
            "ClosestPort": null,
            "Currency": "Cur",
            "PhoneNumber": "PH",
            "Email": "email",
            "VATNumber": "vat",
            "RegisteredNumber": "reg"
        }, {
            "Type": "DeliveryTo",
            "Code": "POSTDLV",
            "IsActive": true,
            "FullName": "Delivery Name",
            "ClosestPort": null,
            "Currency": "",
            "PhoneNumber": "012",
            "Email": "recption@email.com",
            "VATNumber": "572018555",
            "RegisteredNumber": "RegisterNumber"
        }, {
            "Type": "Owner",
            "Code": "POSTOWN",
            "IsActive": true,
            "FullName": "Owner Name",
            "ClosestPort": "",
            "Currency": null,
            "PhoneNumber": "0123",
            "Email": null,
            "VATNumber": null,
            "RegisteredNumber": null
        }, {
            "Type": "PickupFrom",
            "Code": "DECNTAZ-0001175",
            "IsActive": true,
            "FullName": "DECNTAZ-0001175",
            "ClosestPort": null,
            "Currency": null,
            "PhoneNumber": null,
            "Email": null,
            "VATNumber": null,
            "RegisteredNumber": null,
            "EDICode": "DECNTAZ",
            "ExternalCode": null,
            "Address": null
        }],
        "ParentOrderNumber": null,
        "OrderLines": [{
            "LineNo": 5,
            "Partno": "you",
            "Description": "me",
            "UnitOfQuantity": "PC",
            "Quantity": 50,
            "QtyInvoiced": 40,
            "QtyBooked": null,
            "QtyReceived": 30,
            "QtyShipped": 20,
            "Volume": 0,
            "UnitOfVolume": "",
            "Weight": 0,
            "UnitOfWeight": "",
            "ItemPrice": 10,
            "LinePrice": 200,
            "Length": 0,
            "Width": 0,
            "Height": 0,
            "DimUnit": "",
            "DangerousGoodsRef": null,
            "ContainerNumber": "",
            "HarmonisedCode": "HC",
            "PackLineId": "",
            "InvoiceNumber": "",
            "ConfirmationNumber": "",
            "PartAttrib1": "",
            "PartAttrib2": "",
            "PartAttrib3": "",
            "SpecialInstructions": "SI",
            "AdditionalInfo": "AI",
            "ContractNumber": "CN",
            "OriginCountry": "CO",
            "DecimalPlaces": 0,
            "QuantityPerUnit": 0,
            "NetWeight": 0,
            "TransportMode": "AIR",
            "EarliestShipDate": null,
            "LatestShipDate": null,
            "FreightClass": null,
            "ServiceLevel": null,
            "Inners": {
                "Value": 30.5,
                "Unit": "M3"
            },
            "Outers": {
                "Value": 10,
                "Unit": "KG"
            },
            "Parties": [],
            "EstimatedExWorksDate": "2019-07-02T06:51:50.13Z",
            "ExWorksRequiredBy": "2019-07-02T06:51:50.13Z",
            "DeliveryRequiredBy": "2019-07-02T06:51:50.13Z",
            "CustomFields": []
        }]
    }
}