







GET api.dsv.com/om/v2/Orders/31132 HTTP/1.1
Authorization: Basic ZHN2YXBpQHNjYW5wYW4uZGs6RHN2QXBpMTIh
Host: api.dsv.com
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
DSV-Subscription-Key: 0c249f89a7074657aaf2be362d713ca6


