#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
report 50002 "Customs Declaration"

{
	AdditionalSearchTerms = 'Scanpan';
	Caption = 'Customs Declaration';
	WordLayout = './Layouts/CustomsDeclaration.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem("Company Information";"Company Information")
		{
			CalcFields = Picture;
			DataItemTableView = sorting("Primary Key");
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_CompanyInformation; ReportForNavWriteDataItem('CompanyInformation',"Company Information")) {}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('CompanyInformation',"Company Information");
			end;
		}
		dataitem(Item;Item)
		{
			CalcFields = Inventory;
			DataItemTableView = where("Gen. Prod. Posting Group" = FILTER('BRUND' | 'INTERN' | 'EKSTERN')
			//, Quality = FILTER(1)
			//, "ABCD Category" = FILTER('A|A+|B')
			);
			RequestFilterFields = "No.", "Gen. Prod. Posting Group", Quality, "ABCD Category";
			column(ReportForNavId_2; 2) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Item; ReportForNavWriteDataItem('Item',Item)) {}
			column(ReportLanguageCode; ReportLanguageCode)
			{
				IncludeCaption = false;
			}
			column(ReportCaptionName; ReportCaptionName)
			{
				IncludeCaption = false;
			}
			dataitem("Item Translation";"Item Translation")
			{
				RequestFilterFields = "Language Code";
				DataItemLink = "Item No." = FIELD("No.");
				column(ReportForNavId_3; 3) {} // Autogenerated by ForNav - Do not delete
				column(ReportForNav_ItemTranslation; ReportForNavWriteDataItem('ItemTranslation',"Item Translation")) {}
				column(ItemUnitMeasureSALESLength; ItemUnitMeasureSALESLength)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureSALESWidth; ItemUnitMeasureSALESWidth)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureSALESHeight; ItemUnitMeasureSALESHeight)
				{
					IncludeCaption = false;
				}
				column(ItemCrossReferenceSALESReferenceNo; ItemReferenceSALESReferenceNo)
				{
					IncludeCaption = false;
				}
				column(ItemSALESNetWeight; ItemSALESNetWeight)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureSALESGrossWeight; ItemUnitMeasureSALESGrossWeight)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureSALESCubage; ItemUnitMeasureSALESCubage)
				{
					IncludeCaption = false;
				}
				column(ItemSALESTariffNo; ItemSALESTariffNo)
				{
					IncludeCaption = false;
				}
				column(ItemSALESCountryOfOriginLookupName; ItemSALESCountryOfOriginLookupName)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureINNERQuantity; ItemUnitMeasureINNERQuantity)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureINNERLength; ItemUnitMeasureINNERLength)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureINNERWidth; ItemUnitMeasureINNERWidth)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureINNERHeight; ItemUnitMeasureINNERHeight)
				{
					IncludeCaption = false;
				}
				column(ItemCrossReferenceINNERReferenceNo; ItemCrossReferenceINNERReferenceNo)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureINNERGrossWeight; ItemUnitMeasureINNERGrossWeight)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureINNERCubage; ItemUnitMeasureINNERCubage)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureOUTERQuantity; ItemUnitMeasureOUTERQuantity)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureOUTERLength; ItemUnitMeasureOUTERLength)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureOUTERWidth; ItemUnitMeasureOUTERWidth)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureOUTERHeight; ItemUnitMeasureOUTERHeight)
				{
					IncludeCaption = false;
				}
				column(ItemCrossReferenceOUTERReferenceNo; ItemReferenceOUTERReferenceNo)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureOUTERGrossWeight; ItemUnitMeasureOUTERGrossWeight)
				{
					IncludeCaption = false;
				}
				column(ItemUnitMeasureOUTERCubage; ItemUnitMeasureOUTERCubage)
				{
					IncludeCaption = false;
				}
				trigger OnPreDataItem();
				begin
					ReportForNav.OnPreDataItem('ItemTranslation',"Item Translation");
				end;
			}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('Item',Item);
			end;
			trigger OnAfterGetRecord();
			begin
				//Reset
			
				ItemSALESNetWeight := 0;
				ItemUnitMeasureSALESGrossWeight := 0;
				ItemUnitMeasureSALESCubage := 0;
				ItemSALESTariffNo := '';
			
				ItemSALESCountryOfOriginLookupName := '';
			
				ItemUnitMeasureINNERQuantity := 0;
				ItemUnitMeasureINNERLength := 0;
				ItemUnitMeasureINNERWidth := 0;
				ItemUnitMeasureINNERHeight := 0;
				ItemCrossReferenceINNERReferenceNo := '';
				ItemUnitMeasureINNERGrossWeight := 0;
				ItemUnitMeasureINNERCubage := 0;
			
				ItemUnitMeasureOUTERQuantity := 0;
				ItemUnitMeasureOUTERLength := 0;
				ItemUnitMeasureOUTERWidth := 0;
				ItemUnitMeasureOUTERHeight := 0;
				ItemReferenceOUTERReferenceNo := '';
				ItemUnitMeasureOUTERGrossWeight := 0;
				ItemUnitMeasureOUTERCubage := 0;
			
			
				//Sales Item
				ItemUnitofMeasure.Reset();
				ItemUnitofMeasure.SetFilter("Item No.", Item."No.");
				ItemUnitofMeasure.SetFilter(Code, Item."Base Unit of Measure");
				if ItemUnitofMeasure.FindFirst() then begin
					ItemUnitMeasureSALESLength := ItemUnitofMeasure.Length;
					ItemUnitMeasureSALESWidth := ItemUnitofMeasure.Width;
					ItemUnitMeasureSALESHeight := ItemUnitofMeasure.Height;
					ItemUnitMeasureSALESGrossWeight := ItemUnitofMeasure.Weight;
					ItemUnitMeasureSALESCubage := ItemUnitofMeasure.Cubage;
				end;
			
				ItemReference.Reset();
				ItemReference.SetFilter("Item No.", item."No.");
				ItemReference.SetFilter("Reference Type", '%1', 3);
				ItemReference.SetFilter("Unit of Measure", Item."Base Unit of Measure");
				If ItemReference.FindFirst then begin
					ItemReferenceSALESReferenceNo := ItemReference."Reference No.";
				end;
			
				ItemSALESNetWeight := Item."Net Weight";
				ItemSALESTariffNo := Item."Tariff No.";
			
				ItemSALESCountryOfOriginLookupName := Item."Country/Region of Origin Code";
			
				//INNER,,MASTER Item
				ItemUnitofMeasure.Reset();
				ItemUnitofMeasure.SetFilter("Item No.", Item."No.");
				ItemUnitofMeasure.SetFilter(Code, 'INNER');
				if ItemUnitofMeasure.FindFirst() then begin
					ItemUnitMeasureINNERQuantity := ItemUnitofMeasure."Qty. per Unit of Measure";
					ItemUnitMeasureINNERLength := ItemUnitofMeasure.Length;
					ItemUnitMeasureINNERWidth := ItemUnitofMeasure.Width;
					ItemUnitMeasureINNERHeight := ItemUnitofMeasure.Height;
					ItemUnitMeasureINNERGrossWeight := ItemUnitofMeasure.Weight;
					ItemUnitMeasureINNERCubage := ItemUnitofMeasure.Cubage;
				end;
			
				ItemReference.Reset();
				ItemReference.SetFilter("Item No.", item."No.");
				ItemReference.SetFilter("Reference Type", '%1', 3);
				ItemReference.SetFilter("Unit of Measure", '%1|%2', 'INNER', 'INNER');
				If ItemReference.FindFirst() then begin
					ItemCrossReferenceINNERReferenceNo := ItemReference."Reference No.";
				end;
			
			
				//OUTER Item
				ItemReference.Reset();
				ItemReference.SetFilter("Item No.", item."No.");
				ItemReference.SetFilter("Reference Type", '%1', 3);
				ItemReference.SetFilter("Unit of Measure", '%1|%2', 'MASTER', 'OUTER');
				If ItemReference.FindFirst() then begin
					ItemReferenceOUTERReferenceNo := ItemReference."Reference No.";
				end;
			
				ItemUnitofMeasure.Reset();
				ItemUnitofMeasure.SetFilter("Item No.", Item."No.");
				ItemUnitofMeasure.SetFilter(Code, '%1|%2', 'MASTER', 'OUTER');
				if ItemUnitofMeasure.FindFirst() then begin
					ItemUnitMeasureOUTERQuantity := ItemUnitofMeasure."Qty. per Unit of Measure";
					ItemUnitMeasureOUTERLength := ItemUnitofMeasure.Length;
					ItemUnitMeasureOUTERWidth := ItemUnitofMeasure.Width;
					ItemUnitMeasureOUTERHeight := ItemUnitofMeasure.Height;
					ItemUnitMeasureOUTERGrossWeight := ItemUnitofMeasure.Weight;
					ItemUnitMeasureOUTERCubage := ItemUnitofMeasure.Cubage;
				end;
			
			end;
			
		}
	}
	requestpage
	{
		SaveValues = true;
		layout
		{
			area(Content)
			{
				group(Scanpan)
				{
					Caption = 'Scanpan';

					field(ReportLanguageOption; ReportLanguageOpt)
					{
						Caption = 'Select report language';
						ToolTip = 'What language format the report should be in.';
						OptionCaption = 'Dansk,English';
						ApplicationArea = Basic;
					}
				}
				group(Options)
				{
					Visible = false;
					Caption = 'Options';
				}
			}
		}
		trigger OnOpenPage()
		begin
			
		end;

	}
	labels
	{
		LabelName = 'Label Text';
	}

	local procedure getItemUnitofMeasure()
	begin

	end;

	trigger OnInitReport()
	begin
		;ReportsForNavInit;
	end;

	trigger OnPostReport()
	begin
	end;

	trigger OnPreReport()
	begin
		;
		//Language
		ReportLanguageCode := 'ENU';
		ReportCaptionName := 'Customs Declaration';
		if ReportLanguageOpt = 0 then begin
			ReportLanguageCode := 'DAN';
			ReportCaptionName := 'Toldangivelse';
		end;
		CurrReport.LANGUAGE := CU43.GetLanguageId(ReportLanguageCode);  //GetLanguageID(ReportLanguageCode);


		;ReportsForNavPre;
	end;
	var
		//Varables here

		//Report fields
		ItemUnitMeasureSALESLength: Decimal;
		ItemUnitMeasureSALESWidth: Decimal;
		ItemUnitMeasureSALESHeight: Decimal;

		ItemReferenceSALESReferenceNo: Text[50];

		ItemSALESNetWeight: Decimal;
		ItemUnitMeasureSALESGrossWeight: Decimal;
		ItemUnitMeasureSALESCubage: Decimal;
		ItemSALESTariffNo: Text[20];

		ItemSALESCountryOfOriginLookupName: Text[100];

		ItemUnitMeasureINNERQuantity: Decimal;
		ItemUnitMeasureINNERLength: Decimal;
		ItemUnitMeasureINNERWidth: Decimal;
		ItemUnitMeasureINNERHeight: Decimal;
		ItemCrossReferenceINNERReferenceNo: Text[50];
		ItemUnitMeasureINNERGrossWeight: Decimal;
		ItemUnitMeasureINNERCubage: Decimal;

		ItemUnitMeasureOUTERQuantity: Decimal;
		ItemUnitMeasureOUTERLength: Decimal;
		ItemUnitMeasureOUTERWidth: Decimal;
		ItemUnitMeasureOUTERHeight: Decimal;
		ItemReferenceOUTERReferenceNo: Text[50];
		ItemUnitMeasureOUTERGrossWeight: Decimal;
		ItemUnitMeasureOUTERCubage: Decimal;
		//



		ReportLanguageOpt: Option;
		ReportLanguageCode: Code[10];
		ReportCaptionName: Text[50];
		//Records here
		ItemUnitofMeasure: Record "Item Unit of Measure";

		ItemReference: record "Item Reference";

		//CodeUnits here
		CU43: Codeunit Language;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
			'Item':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$Item$CurrentKey$Text',Item.CurrentKey); GlobalLanguage := currLanguage;
				end;
			'ItemTranslation':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$ItemTranslation$CurrentKey$Text',"Item Translation".CurrentKey); GlobalLanguage := currLanguage;
				end;
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

