#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
Report 50012 DebitorAddress
{
    AdditionalSearchTerms = 'Scanpan';
    Caption = 'DebitorAddress';
    DefaultLayout = Word;
    WordLayout = './Layouts/DebitorAddress.docx';

    dataset
    {
        dataitem(Customer; Customer)
        {
            RequestFilterFields = Blocked, "Country/Region Code", "Salesperson Code";
            column(ReportForNav_Customer; ReportForNavWriteDataItem('Customer', Customer)) { }
            column(ReportForNavId_1; 1) { } // Autogenerated by ForNav - Do not delete
            dataitem(CDOE_MailRecipient; "CDO E-Mail Recipient")
            {
                DataItemLink = "No." = FIELD("No.");
                DataItemTableView = where(Table = CONST(0));
                RequestFilterFields = "Document Code";
                column(ReportForNav_CDOE_MailRecipient; ReportForNavWriteDataItem('CDOE_MailRecipient', CDOE_MailRecipient)) { }
                column(ReportForNavId_2; 2) { } // Autogenerated by ForNav - Do not delete
                trigger OnPreDataItem();
                begin
                    ReportForNav.OnPreDataItem('CDOE_MailRecipient', CDOE_MailRecipient);
                end;
            }
            trigger OnPreDataItem();
            begin
                ReportForNav.OnPreDataItem('Customer', Customer);
            end;
        }
    }
    requestpage
    {
        SaveValues = false;
        layout
        {
        }

    }

    trigger OnInitReport()
    begin
        ;
        ReportsForNavInit;

    end;

    trigger OnPreReport()
    begin
        ;
        ReportsForNavPre;
    end;

    trigger OnPostReport()
    begin
    end;

    // --> Reports ForNAV Autogenerated code - do not delete or modify
    var
        ReportForNav: Codeunit "ForNAV Report Management";
        ReportForNavInitialized: Boolean;
        ReportForNavShowOutput: Boolean;
        ReportForNavTotalsCausedBy: Integer;

    local procedure ReportsForNavInit()
    var
        id: Integer;
        FormatRegion: Text;
    begin
        Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
        ReportForNav.OnInit(id);
    end;

    local procedure ReportsForNavPre()
    begin
    end;

    local procedure ReportForNavSetTotalsCausedBy(value: Integer)
    begin
        ReportForNavTotalsCausedBy := value;
    end;

    local procedure ReportForNavSetShowOutput(value: Boolean)
    begin
        ReportForNavShowOutput := value;
    end;

    local procedure ReportForNavInit(jsonObject: JsonObject)
    begin
        ReportForNav.Init(jsonObject, CurrReport.ObjectId);
    end;

    local procedure ReportForNavWriteDataItem(dataItemId: Text; rec: Variant): Text
    var
        currLanguage: Integer;
        jsonObject: JsonObject;
        values: Text;
    begin
        if not ReportForNavInitialized then begin
            ReportForNavInit(jsonObject);
            ReportForNavInitialized := true;
        end;

        case (dataItemId) of
            'Customer':
                begin
                    currLanguage := GlobalLanguage;
                    GlobalLanguage := 1033;
                    jsonObject.Add('DataItem$Customer$CurrentKey$Text', Customer.CurrentKey);
                    GlobalLanguage := currLanguage;
                end;
            'CDOE_MailRecipient':
                begin
                    currLanguage := GlobalLanguage;
                    GlobalLanguage := 1033;
                    jsonObject.Add('DataItem$CDOE_MailRecipient$CurrentKey$Text', CDOE_MailRecipient.CurrentKey);
                    GlobalLanguage := currLanguage;
                end;
        end;
        ReportForNav.AddDataItemValues(jsonObject, dataItemId, rec);
        jsonObject.WriteTo(values);
        exit(values);
    end;
    // Reports ForNAV Autogenerated code - do not delete or modify -->
}

