#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings



report 50013 EmployeeSales
{
	AdditionalSearchTerms = 'Scanpan';
	Caption = 'Employee Sales';
	WordLayout = './Layouts/EmployeeSales.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem(Customer;Customer)
		{
			DataItemTableView = where("No." = filter(1027 | 1029 | 1039));
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Customer; ReportForNavWriteDataItem('Customer',Customer)) {}
			dataitem("Cust. Ledger Entry";"Cust. Ledger Entry")
			{
				CalcFields = "Remaining Amt. (LCY)";
				DataItemLink = "Customer No." = FIELD("No.");
				DataItemTableView = where(Open = const(true));
				column(ReportForNavId_2; 2) {} // Autogenerated by ForNav - Do not delete
				column(ReportForNav_CustLedgerEntry; ReportForNavWriteDataItem('CustLedgerEntry',"Cust. Ledger Entry")) {}
				dataitem("Sales Invoice Header";"Sales Invoice Header")
				{
					RequestFilterFields = "No.";
					DataItemLink = "No." = FIELD("Document No.");
					column(ReportForNavId_3; 3) {} // Autogenerated by ForNav - Do not delete
					column(ReportForNav_SalesInvoiceHeader; ReportForNavWriteDataItem('SalesInvoiceHeader',"Sales Invoice Header")) {}
					trigger OnPreDataItem();
					begin
						ReportForNav.OnPreDataItem('SalesInvoiceHeader',"Sales Invoice Header");
					end;
				}
				trigger OnPreDataItem();
				begin
					ReportForNav.OnPreDataItem('CustLedgerEntry',"Cust. Ledger Entry");
				end;
			}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('Customer',Customer);
			end;
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
		}

	}

	trigger OnInitReport()
	begin
		;ReportsForNavInit;

	end;

	trigger OnPostReport()
	begin
	end;

	trigger OnPreReport()
	begin
		;ReportsForNavPre;
	end;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
			'Customer':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$Customer$CurrentKey$Text',Customer.CurrentKey); GlobalLanguage := currLanguage;
				end;
			'CustLedgerEntry':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$CustLedgerEntry$CurrentKey$Text',"Cust. Ledger Entry".CurrentKey); GlobalLanguage := currLanguage;
				end;
			'SalesInvoiceHeader':
				begin
					CurrReport.Language := ReportForNav.GetLanguageID("Sales Invoice Header"."Language Code");
					jsonObject.Add('CurrReport$Language$Integer',CurrReport.Language);
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$SalesInvoiceHeader$CurrentKey$Text',"Sales Invoice Header".CurrentKey); GlobalLanguage := currLanguage;
				end;
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

