#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings















Report 50014 "ForNAV 50014"
{
	WordLayout = './Layouts/ForNAV50014.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem(Integer;Integer)
		{
			MaxIteration = 1;
			DataItemTableView = sorting(Number) where(Number = FILTER(1 ..));
			column(ReportForNavId_3; 3) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Integer; ReportForNavWriteDataItem('Integer',Integer)) {}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('Integer',Integer);
			end;
		}
		dataitem(Customer;Customer)
		{
			DataItemTableView = where("Country/Region Code" = FILTER(<> 'DK'));
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Customer; ReportForNavWriteDataItem('Customer',Customer)) {}
			dataitem("Cust. Ledger Entry";"Cust. Ledger Entry")
			{
				CalcFields = "Amount (LCY)";
				DataItemLink = "Customer No." = FIELD("No.");
				DataItemTableView = where(Open = CONST(true));
				column(ReportForNavId_2; 2) {} // Autogenerated by ForNav - Do not delete
				column(ReportForNav_CustLedgerEntry; ReportForNavWriteDataItem('CustLedgerEntry',"Cust. Ledger Entry")) {}
				column(LineNo; LineNo)
				{
					IncludeCaption = false;
				}
				column(StartingDate; StartingDate)
				{
					IncludeCaption = false;
				}
				column(EndingDate; EndingDate)
				{
					IncludeCaption = false;
				}
				trigger OnPreDataItem();
				begin
					"Cust. Ledger Entry".SetRange("Posting Date", StartingDate, EndingDate);
					"Cust. Ledger Entry".SetView(ReportForNav.OnPreDataItemView('CustLedgerEntry',"Cust. Ledger Entry"));
				end;
				
				trigger OnAfterGetRecord();
				var
					SetSKip: Boolean;
				begin
					LineNo += 1;
					SetSkip := false;
					if CountryRegion.Get(Customer."Country/Region Code") then begin
						SetSKip := false;
						if CountryRegion."EU Country/Region Code" = '' then SetSKip := true;
					end else
						SetSkip := true;
					if SetSKip = true then CurrReport.Skip();
				end;
				
			}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('Customer',Customer);
			end;
		}
		dataitem(Integer2;Integer)
		{
			MaxIteration = 1;
			DataItemTableView = sorting(Number) where(Number = FILTER(1 ..));
			column(ReportForNavId_4; 4) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Integer2; ReportForNavWriteDataItem('Integer2',Integer2)) {}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('Integer2',Integer2);
			end;
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
			area(Content)
			{
				group(Scanpan)
				{
					Caption = 'Scanpan';
					field(StartingDate; StartingDate)
					{
						ApplicationArea = Basic;
						Caption = 'Start date';
					}
					field(EndingDate; EndingDate)
					{
						ApplicationArea = Basic;
						Caption = 'End date';
					}
				}
				group(Options)
				{
					Caption = 'Options';
				}
			}
		}

	}
	var
		CountryRegion: Record "Country/Region";
		LineNo: Integer;
		StartingDate: Date;
		EndingDate: Date;

	trigger OnInitReport()
	begin
		;ReportsForNavInit;

	end;

	trigger OnPostReport()
	begin
	end;

	trigger OnPreReport()
	begin
		;ReportsForNavPre;
		//"Cust. Ledger Entry".SetFilter("Posting Date",'%1..%2', StartingDate,EndingDate);
	end;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
			'Customer':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$Customer$CurrentKey$Text',Customer.CurrentKey); GlobalLanguage := currLanguage;
				end;
			'CustLedgerEntry':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$CustLedgerEntry$CurrentKey$Text',"Cust. Ledger Entry".CurrentKey); GlobalLanguage := currLanguage;
				end;
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

