#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
Report 50007 Licenseplate
{
	AdditionalSearchTerms = 'Scanpan';
	Caption = 'Licenseplate';
	WordLayout = './Layouts/Licenseplate.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem(Integer;Integer)
		{
			MaxIteration = 100;
			DataItemTableView = sorting(Number);
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_IntegerREC; ReportForNavWriteDataItem('IntegerREC',Integer)) {}
			column(LabelID; LabelID)
			{
				IncludeCaption = false;
			}
			column(Counter; Counter)
			{
				IncludeCaption = false;
			}
			column(AntalLabels; AntalLabels)
			{
				IncludeCaption = false;
			}
			trigger OnPreDataItem();
			begin
				Integer.SetRange(Number, 1, AntalLabels);
				if AntalLabels = 0 then Error('Du skal vælge et antal labels til udskrift');
				if AntalLabels > 100 then Error('Du kan ikke vælge mere end 100 antal labels');
				Integer.SetView(ReportForNav.OnPreDataItemView('IntegerREC',Integer));
			end;
			
			trigger OnAfterGetRecord();
			begin
				if LabelID = '' then begin
					CounterValidate := NoSeriesMgt.GetNextNo('L-LICENCEPLTE', WorkDate(), TRUE);
					IF StrLen(CounterValidate) > 10 then Error('Stergkodelængde kan maks. være 10 tegn. Juster Nummerserie.');
					Counter := CounterValidate
				end
				else begin
					CounterValidate := LabelID;
					IF StrLen(CounterValidate) > 10 then Error('Stergkodelængde kan maks. være 10 tegn.');
					Counter := CounterValidate;
			
				end;
			
			
			end;
			
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
			area(Content)
			{
				group(scanpan)
				{
					Caption = 'Scanpan';
					field(AntalLabels; AntalLabels)
					{
						ApplicationArea = Basic;
						Caption = 'Antal plukkelabels til udskrift';
						ToolTip = 'Vælg hvor mange plukkelabels der skal udskrives. Maks. 100 stk. pr. udskrift.';
					}
					field(LabelID; LabelID)
					{
						ApplicationArea = Basic;
						Caption = 'Manuel kode';
						ToolTip = 'Her kan der angives en bestemt kode til udskrift. Det er samme kode, der skrive på alle antal labels der bestilles.';

					}
				}
				group(Options)
				{
					Caption = 'Options';
				}
			}
		}
		trigger OnOpenPage()
		begin
			
		end;

	}

	trigger OnInitReport()
	begin
		;ReportsForNavInit;

		//SCANPAN

	end;

	trigger OnPostReport()
	begin
	end;

	trigger OnPreReport()
	begin
		;ReportsForNavPre;

	end;
	var
		AntalLabels: Integer;
		LabelID: Text[10];
		Counter: Text[10];
		CounterValidate: Text[30];
		//RECORDS
		NoSeriesLine: Record "No. Series Line";
		//CODEUNIT
		NoSeriesMgt: Codeunit NoSeriesManagement;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

