#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings
Report 50010 Ordrebeholdning
{
	AdditionalSearchTerms = 'Scanpan';
	caption = 'Order Inventory';
	WordLayout = './Layouts/Ordrebeholdning.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem("Company Information";"Company Information")
		{
			column(ReportForNavId_3; 3) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_CompanyInformation; ReportForNavWriteDataItem('CompanyInformation',"Company Information")) {}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('CompanyInformation',"Company Information");
			end;
		}
		dataitem("Sales Line";"Sales Line")
		{
			DataItemTableView = sorting("Document Type", "Document No.", Type, "Line No.") where("Document Type" = CONST(1));
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_SalesLine; ReportForNavWriteDataItem('SalesLine',"Sales Line")) {}
			column(ReportCaptionName; ReportCaptionName)
			{
				IncludeCaption = false;
			}
			column(LanguageSelected; LanguageSelectedCode)
			{
				IncludeCaption = false;
			}
			column(ReportLanguageCode; ReportLanguageCodeCode)
			{
				IncludeCaption = false;
			}
			column(ItemTranslationText; ItemTranslationText)
			{
				IncludeCaption = false;
			}
			dataitem("Sales Header";"Sales Header")
			{
				DataItemLink = "Document Type" = FIELD("Document Type"), "No." = FIELD("Document No.");
				DataItemTableView = sorting("Document Type", "No.") where("Document Type" = CONST(Order));
				RequestFilterFields = "No.", "Sell-to Customer No.", "External Document No.", "Shipment Date";
				column(ReportForNavId_2; 2) {} // Autogenerated by ForNav - Do not delete
				column(ReportForNav_SalesHeader; ReportForNavWriteDataItem('SalesHeader',"Sales Header")) {}
				trigger OnPreDataItem();
				begin
					ReportForNav.OnPreDataItem('SalesHeader',"Sales Header");
				end;
			}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('SalesLine',"Sales Line");
			end;
			trigger OnAfterGetRecord();
			var
				sl: Record "Sales Line";
			begin
				ItemTranslationText := LookupItemTranslation("Sales Line"."No.", LanguageSelectedCode);
			end;
			
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
			area(Content)
			{
				group(Scanpan)
				{
					Caption = 'Scanpan';
					label(explainer)
					{
						ApplicationArea = Basic, Suite;
						Caption = '** To export;choose Excel(data and layout)';
					}
					field(ReportLanguageOption; ReportLanguageOptionOpt)
					{
						ApplicationArea = Basic;
						//Caption = 'Select report language';
						Caption = 'Report Caption Language';
						OptionCaption = 'Dansk,English';
					}

					field(LanguageSelected; LanguageSelectedCode)
					{
						ApplicationArea = Basic;
						//Caption = 'Sprog';
						Caption = 'Item language';
						TableRelation = Language.Code;

						trigger OnLookup(var Text: Text): Boolean
						var
							rLanguage: Record Language;
						begin
							rLanguage.SetFilter(Code, 'DEU|DAN|ENU|NOR|FIN|FRA|NLD|SVE|BEL');
							if page.RunModal(Page::Languages, rLanguage) = Action::LookupOK then LanguageSelectedCode := rLanguage.Code;

						end;
					}
				}
				group(Options)
				{
					Caption = 'Options';
				}
			}
		}

	}

	trigger OnInitReport()
	begin
		;ReportsForNavInit;

	end;

	trigger OnPreReport()
	begin
		//Language
		ReportLanguageCodeCode := 'ENU';
		ReportCaptionName := 'Order status';
		IF ReportLanguageOptionOpt = 0 THEN begin
			ReportLanguageCodeCode := 'DAN';
			ReportCaptionName := 'Ordrebeholdning';
		end;

		//CurrReport.LANGUAGE := ReportLanguage.GetLanguageID(ReportLanguageCode);

		CurrReport.LANGUAGE := LanguageCU.GetLanguageID(ReportLanguageCodeCode);

		;ReportsForNavPre;
	end;

	trigger OnPostReport()
	begin
	end;
	var
		//TABLES
		//ReportLanguage: Record Language;
		LanguageCU: Codeunit Language;
		ReportLanguageCodeCode: Code[10];
		//VARIABLES
		LanguageSelectedCode: Code[20];
		ReportLanguageOptionOpt: Option;
		ReportCaptionName: Text[50];
		ItemTranslationText: Text[200];

    local procedure LookupItemTranslation(ItemNo: code[20]; LanguageID: code[20]): Text[200];
    var
        ItemTranslation: Record "Item Translation";
    begin
        ItemTranslation.SetFilter("Item No.", ItemNo);
        ItemTranslation.SetFilter("Language Code", LanguageID);
        if ItemTranslation.FindFirst() then
            exit(ItemTranslation.Description) else
            exit("Sales Line".Description);


    end;



	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
			'CompanyInformation':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$CompanyInformation$CurrentKey$Text',"Company Information".CurrentKey); GlobalLanguage := currLanguage;
				end;
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

