#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings






report 50011 PalletShipmentReport
{
	AdditionalSearchTerms = 'Scanpan';
	Caption = 'Pallet Shipment Report';
	WordLayout = './Layouts/PalletShipmentReport.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem(Integer;Integer)
		{
			DataItemTableView = sorting(Number) where(Number = FILTER(1 ..));
			MaxIteration = 1;
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_Integer; ReportForNavWriteDataItem('Integer',Integer)) {}
			dataitem("Posted Whse. Shipment Header";"Posted Whse. Shipment Header")
			{
				RequestFilterFields = "No.", "Whse. Shipment No.";
				column(ReportForNavId_2; 2) {} // Autogenerated by ForNav - Do not delete
				column(ReportForNav_PostedWhseShipmentHeader; ReportForNavWriteDataItem('PostedWhseShipmentHeader',"Posted Whse. Shipment Header")) {}
				column(ItemDescription; ItemDescription)
				{
					IncludeCaption = false;
				}
				column(NameShipTo; NameShipTo)
				{
					IncludeCaption = false;
				}
				dataitem("MOB License Plate";"MOB License Plate")
				{
					DataItemLink = "Whse. Document No." = FIELD("No.");
					column(ReportForNavId_3; 3) {} // Autogenerated by ForNav - Do not delete
					column(ReportForNav_MOBLicensePlate; ReportForNavWriteDataItem('MOBLicensePlate',"MOB License Plate")) {}
					column(MOBLicensePlateRecordNo; MOBLicensePlateRecordNo)
					{
						IncludeCaption = false;
					}
					column(TotalCubage; TotalCubage)
					{
						IncludeCaption = false;
					}
					column(TotalPalletWeight; TotalPalletWeight)
					{
						IncludeCaption = false;
					}
					dataitem("MOB License Plate Content";"MOB License Plate Content")
					{
						DataItemLink = "License Plate No." = FIELD("No.");
						column(ReportForNavId_4; 4) {} // Autogenerated by ForNav - Do not delete
						column(ReportForNav_MOBLicensePlateContent; ReportForNavWriteDataItem('MOBLicensePlateContent',"MOB License Plate Content")) {}
						column(TotalItemBTWeight; TotalItemGrossWeight)
						{
							IncludeCaption = false;
						}
						column(TotalItemNTWeight; TotalItemNetWeight)
						{
							IncludeCaption = false;
						}
						column(TotalQuantity; TotalQuantity)
						{
							IncludeCaption = false;
						}
						trigger OnPreDataItem();
						begin
							ReportForNav.OnPreDataItem('MOBLicensePlateContent',"MOB License Plate Content");
						end;
						trigger OnAfterGetRecord();
						var
							Item: Record Item;
							PostedWhseShipmentLine: Record "Posted Whse. Shipment Line";
						begin
							//Quantity
							TotalQuantity += Quantity;
							PostedWhseShipmentLine.Reset();
							PostedWhseShipmentLine.SetFilter("No.", "MOB License Plate Content"."Whse. Document No.");
							PostedWhseShipmentLine.SetFilter("Item No.", '%1', "MOB License Plate Content"."No.");
							ItemDescription := '';
						
							//ItemWeights
							Item.Reset();
							if Item.Get("MOB License Plate Content"."No.") then begin
								TotalItemGrossWeight += (Item."Gross Weight" * "MOB License Plate Content".Quantity);
								TotalItemNetWeight += (Item."Net Weight" * "MOB License Plate Content".Quantity);
							end;
						
							//ItemDescription
							if PostedWhseShipmentLine.FindFirst() then ItemDescription := PostedWhseShipmentLine.Description;
							//Try Item Card
							if ItemDescription = '' then begin
								Item.Reset;
								if Item.Get("MOB License Plate Content"."No.") then
									ItemDescription := Item.Description;
							end;
						end;
						
					}
					trigger OnPreDataItem();
					begin
						ReportForNav.OnPreDataItem('MOBLicensePlate',"MOB License Plate");
					end;
					trigger OnAfterGetRecord();
					begin
						MOBLicensePlateRecordNo += 1;
					
						//Cubage
						TotalCubage += (("MOB License Plate".Height * "MOB License Plate".Width * "MOB License Plate".Length) / 1000000);
					
						//PalletWeight
						TotalPalletWeight += "MOB License Plate".Weight;
					end;
					
				}
				trigger OnPreDataItem();
				begin
					ReportForNav.OnPreDataItem('PostedWhseShipmentHeader',"Posted Whse. Shipment Header");
				end;
				trigger OnAfterGetRecord();
				var
					PostedWhseShipmentLine: Record "Posted Whse. Shipment Line";
					SalesHeader: Record "Sales Header";
					SalesInvoiceHeader: Record "Sales Invoice Header";
				begin
					NameShipTo := '';
				
					PostedWhseShipmentLine.SetFilter("No.", "Posted Whse. Shipment Header"."No.");
					if PostedWhseShipmentLine.FindFirst() then begin
						//Try salesheader
						SalesHeader.Reset();
						SalesHeader.SetRange("Document Type", SalesHeader."Document Type"::Order);
						SalesHeader.SetFilter("No.", PostedWhseShipmentLine."Source No.");
				
						if SalesHeader.FindFirst() then begin
							NameShipTo := SalesHeader."Ship-to Name";
							if NameShipTo = '' then NameShipTo := SalesHeader."Bill-to Name";
						end else begin
							//Try posted invoice
							SalesInvoiceHeader.Reset();
							SalesInvoiceHeader.SetFilter("Order No.", PostedWhseShipmentLine."Source No.");
							if SalesInvoiceHeader.FindFirst() then begin
								NameShipTo := SalesInvoiceHeader."Ship-to Name";
								if NameShipTo = '' then NameShipTo := SalesInvoiceHeader."Bill-to Name";
							end;
						end;
					end;
				end;
				
			}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('Integer',Integer);
			end;
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
			area(Content)
			{
			}
		}

	}
	var

		//CodeUnits here
		CU43: Codeunit Language;

		//Code
		ReportLanguageCode: Code[10];
		TotalCubage: Decimal;
		TotalItemGrossWeight: Decimal;
		TotalItemNetWeight: Decimal;
		TotalPalletWeight: Decimal;

		//Integer
		MOBLicensePlateRecordNo: Integer;
		TotalQuantity: Integer;

		//Option
		ReportLanguageOpt: Option;

		//Text
		ReportCaptionName: Text[50];
		NonKeyFieldValue: Text[100];
		ItemDescription: Text[120];
		NameShipTo: Text[120];
	trigger OnInitReport();
		begin
			;ReportsForNavInit;
		end;
	trigger OnPreReport();
		begin
			;ReportsForNavPre;	end;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
			'PostedWhseShipmentHeader':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$PostedWhseShipmentHeader$CurrentKey$Text',"Posted Whse. Shipment Header".CurrentKey); GlobalLanguage := currLanguage;
				end;
			'MOBLicensePlate':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$MOBLicensePlate$CurrentKey$Text',"MOB License Plate".CurrentKey); GlobalLanguage := currLanguage;
				end;
			'MOBLicensePlateContent':
				begin
					currLanguage := GlobalLanguage; GlobalLanguage := 1033; jsonObject.Add('DataItem$MOBLicensePlateContent$CurrentKey$Text',"MOB License Plate Content".CurrentKey); GlobalLanguage := currLanguage;
				end;
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

