#pragma warning disable AA0005, AA0008, AA0018, AA0021, AA0072, AA0137, AA0201, AA0204, AA0206, AA0218, AA0228, AL0254, AL0424, AS0011, AW0006 // ForNAV settings





Report 50001 ProductionControllingPriority
{
	AdditionalSearchTerms = 'Scanpan';
	Caption = 'Production Controlling Priority Report';
	WordLayout = './Layouts/ProductionControllingPriority.docx'; DefaultLayout = Word;

	dataset
	{
		dataitem("Prod. Order Routing Line";ProdContllingRoutingLinesTMP)
		{
			RequestFilterFields = Status, Priority, ItemNo, "Ressource No.", "Starting Date", "Ending Date";
			DataItemTableView = sorting(Priority) where(Priority = FILTER(<> 0));
			column(ReportForNavId_1; 1) {} // Autogenerated by ForNav - Do not delete
			column(ReportForNav_ProdOrderRoutingLine; ReportForNavWriteDataItem('ProdOrderRoutingLine',"Prod. Order Routing Line")) {}
			trigger OnPreDataItem();
			begin
				ReportForNav.OnPreDataItem('ProdOrderRoutingLine',"Prod. Order Routing Line");
			end;
		}
	}
	requestpage
	{
		SaveValues = false;
		layout
		{
			area(Content)
			{
				group(scanpan)
				{
					Caption = 'Scanpan';

				}
				group(Options)
				{
					Caption = 'Options';
				}
			}
		}

	}
	var
		ScanpanMiscellaneous: Codeunit ScanpanMiscellaneous;

	trigger OnInitReport()
	begin
		ScanpanMiscellaneous.ControllingFillProductionRouteLine("Prod. Order Routing Line");
		;ReportsForNavInit;

	end;

	trigger OnPostReport()
	begin
	end;

	trigger OnPreReport()
	begin
		;ReportsForNavPre;
	end;

	// --> Reports ForNAV Autogenerated code - do not delete or modify
	var
		ReportForNav: Codeunit "ForNAV Report Management";
		ReportForNavTotalsCausedBy: Integer;
		ReportForNavInitialized: Boolean;
		ReportForNavShowOutput: Boolean;

	local procedure ReportsForNavInit()
	var
		id: Integer;
		FormatRegion: Text;
	begin
		Evaluate(id, CopyStr(CurrReport.ObjectId(false), StrPos(CurrReport.ObjectId(false), ' ') + 1));
		ReportForNav.OnInit(id);
	end;
	local procedure ReportsForNavPre() begin end;
	local procedure ReportForNavSetTotalsCausedBy(value : Integer) begin ReportForNavTotalsCausedBy := value; end;
	local procedure ReportForNavSetShowOutput(value : Boolean) begin ReportForNavShowOutput := value; end;
	local procedure ReportForNavInit(jsonObject : JsonObject) begin ReportForNav.Init(jsonObject, CurrReport.ObjectId); end;
	local procedure ReportForNavWriteDataItem(dataItemId: Text; rec : Variant) : Text
	var
		values: Text;
		jsonObject: JsonObject;
		currLanguage: Integer;
	begin
		if not ReportForNavInitialized then begin
			ReportForNavInit(jsonObject);
			ReportForNavInitialized := true;
		end;

		case (dataItemId) of
		end;
		ReportForNav.AddDataItemValues(jsonObject,dataItemId,rec);
		jsonObject.WriteTo(values);
		exit(values);
	end;
	// Reports ForNAV Autogenerated code - do not delete or modify -->
}

